name: Poetry release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Change working directory
      run: cd ${{ github.workspace }}

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Extract Version
      id: extract_version
      run: |
        echo "VERSION=$(poetry version --no-interaction | cut -d ' ' -f 2)" >> $GITHUB_ENV
        echo "The current version that is being published is ${{ env.VERSION }}!"
      shell: bash

    - name: Build
      run: |
        poetry build

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Testing ${{ env.VERSION }}
